openapi: 3.0.0
info:
  title: Product API
  version: 1.0.0
  description: API to fetch a list of products
servers:
  - url: http://localhost:8080
paths:
  /products:
    get:
      summary: Get a list of products
      description: Returns a list of products
      parameters:
        - in: query
          name: category
          schema:
            type: string
          description: Filter products by category
        - in: query
          name: sort
          schema:
            type: string
          description: Sort products by field (e.g., sku, price, description, category, discount)
        - in: query
          name: order
          schema:
            type: string
          description: Sort order (asc or desc)
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    sku:
                      type: string
                    price:
                      type: number
                      format: float
                    description:
                      type: string
                    category:
                      type: string
                    discount:
                      type: number
                      format: float