name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    types:
      - ready_for_review
    branches: [ main ]

env:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build with Maven
        run:
          mvn clean install -B
      - name: Run tests with Maven
        uses: actions/upload-artifact@v3
        with:
          name: maven-build
          path: target/*.jar
          retention-days: 1
          timeout-minutes: 10
